const express = require('express')
const router = express.Router({ mergeParams: true })
const wrapAsync = require('../utils/wrapAsync')
const ExpressError = require('../utils/ExpressError')
const Campground = require('../models/campground')
const { campgroundSchema, reviewSchema } = require('../schemas.js')
const Review = require('../models/review.js')
const { isLoggedIn, reviewAuthor } = require('../middleware.js')
const { validateReview } = require('../middleware.js')
const reviews = require('../controllers/reviews.js')
router.post('/', isLoggedIn, validateReview, wrapAsync(reviews.makeReview))
router.delete('/:reviewId', isLoggedIn, reviewAuthor, wrapAsync(reviews.deleteReviews))
module.exports = router