module.exports.places = [
    "Sunny Meadows Campground",
    "Mountain View Retreat",
    "Lakeside Haven",
    "Forest Glen Camp",
    "Desert Oasis Campground",
    "Riverside Campsite",
    "Seaside Escape",
    "Prairie View Campground",
    "Highland Ridge Camp",
    "Riverbend Retreat",
    "Woodland Springs",
    "Canyon Creek Campground",
    "Hidden Valley Camp",
    "Summit View Campsite",
    "Lakefront Paradise",
    "Desert Mirage Campground",
    "Evergreen Hills Camp",
    "Starry Skies Campground",
    "Wilderness Edge Retreat",
    "Ocean Breeze Campsite",
    "Rustic Pines Campground"
];
module.exports.descriptors = [
    "secluded and serene",
    "breathtaking mountain views",
    "tranquil lake setting",
    "deep forest immersion",
    "sun-drenched desert landscape",
    "peaceful riverside",
    "charming seaside",
    "wide open prairie",
    "picturesque and scenic",
    "remote and untouched",
    "rustic and charming",
    "adventurous and rugged",
    "cozy and comfortable",
    "family-friendly and fun",
    "wildlife-rich environment",
    "refreshingly cool and shaded",
    "starlit and magical",
    "scenic and relaxing",
    "spacious and open",
    "well-equipped and convenient",
    "historic and nostalgic"
];
